version: '3.8'

services:
  # Backend API
  backend:
    build: ./backend
    container_name: voting-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads
    restart: unless-stopped
    networks:
      - voting-network

  # Frontend LED Wall
  ledwall:
    build: ./frontend-ledwall
    container_name: voting-ledwall
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:3001
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - voting-network

  # Frontend PWA
  pwa:
    build: ./frontend-pwa
    container_name: voting-pwa
    ports:
      - "3002:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:3001
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - voting-network

  # Nginx Reverse Proxy (opzionale)
  nginx:
    image: nginx:alpine
    container_name: voting-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - ledwall
      - pwa
    restart: unless-stopped
    networks:
      - voting-network

networks:
  voting-network:
    driver: bridge

volumes:
  uploads: